### ISSUE TITLE
Update mkmf to use perl in environment rather than /usr/bin/perl

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/mkmf#35]
Currently, `mkmf` uses the `/usr/bin/perl` as specified in the shebang:
`#!/usr/bin/perl`

mkmf uses the compiled `Config` module that fails with an error if the running Perl version doesn't match the Perl used to compile the library.

The solution is to use the Perl in the environment, which should match the Perl used the compile `Config.pm`:
`#!/usr/bin/env perl`

**Comment by underwoo** [comment]
@ceblanton will you do the work, or will someone else?

**Comment by ceblanton** [comment]
Ready in #36
