### ISSUE TITLE
Erroneous REPRO/DEBUG logic in linux-intel.mk?

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/mkmf#4]
Lines [48-49](https://github.com/NOAA-GFDL/mkmf/blob/master/templates/linux-intel.mk#L48-L49) of linux-intel.mk read
```bash
endif
ifneq ($(DEBUG),)
```
which in other files (e.g. ncrc-intel.mk) read
```bash
else ifneq ($(DEBUG),)
```
The latter implies that REPRO and DEBUG are exclusive modes while the former suggests you can compile with both REPRO and DEBUG options. Is linux-intel.mk wrong or all the others wrong?

**Comment by underwoo** [comment]
linux-intel.mk is wrong. I will correct this.
