### ISSUE TITLE
Use of -fltconsistency in linux-intel.mk

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/mkmf#5]
FFLAGS_REPRO in linux-intel.mk contains "-fltconsistency" ([Line 25](https://github.com/NOAA-GFDL/mkmf/blob/master/templates/linux-intel.mk#L25)) which leads to bad values for some ocean-only experiments in MOM6. Everything works on Gaea (ncrc-intel.mk) which has "-fp-model source" instead of "-fltconsistency".

Is -fltconsistency preferred? If so, we need to use in on Gaea too and then figure out why the model gives bad values. Otherwise, can we have FFLAGS_REPRO in linux-intel.mk set to the same as ncrc_intel.mk?

**Comment by underwoo** [comment]
-fltconsistency is a deprecated flag. It should be replaced with -fpmodel source.
