### ISSUE TITLE
Catch floating point exceptions in debug build

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/mkmf#6]
In issue NOAA-GFDL/MOM6#194 we discussed making floating point exceptions standard. Given that there may be a performance hit it would be better to do this only in debug builds. 

This issue is to add: 

-fpe0 (intel)
-ffpe-trap=invalid,zero,overflow (gnu) 
-<something> (pgi)

to the debug build in the machine *.mk files.

**Comment by underwoo** [comment]
@nicjhan, please fork and put in the fixes in the make template files as you would like them.  Once done, please put in a pull request.

Once the pull request is in, I will complete the pull request.

**Comment by underwoo** [comment]
@nicjhan did MR #8 fix fully fix this issue?
