### ISSUE TITLE
Change the main branch to `main`

### ISSUE THREAD

**Issue by thomas-robinson** [NOAA-GFDL/mkmf#61]
The main branch of this repository should be renamed `main` to be in-line with modern/current git practices.

**Comment by thomas-robinson** [comment]
Just want to bump this since it's over 4 months old.

**Comment by thomas-robinson** [comment]
Bumping this again

**Comment by ceblanton** [comment]
I thought I could do this, but I can't.

**Comment by underwoo** [comment]
There is no reason to do this.
