### ISSUE TITLE
Add -DEBUG to compiler flags in for debug builds

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/mkmf#7]
It would be good to add -DDEBUG for debug builds. We could use this in MOM6 to enable additional safety checks. Presently we have things hard-coded, e.g. 

#define __DO_SAFETY_CHECKS__
or
#undef __DO_SAFETY_CHECKS__

**Comment by underwoo** [comment]
After speaking with other developers, we have decided against adding a generic macro define to the source, or to the make templates.  We feel it may cause too many unexpected issues.
